// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace grpc {

namespace {


}  // namespace

inline ::google::protobuf::uint32* protobuf_Offsets_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() { return NULL; }
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::internal::DefaultInstanceData* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow/core/protobuf/worker_service.proto", schemas, file_default_instances, protobuf_Offsets_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto(), factory,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
}

void protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_2eproto();
  ::google::protobuf::internal::InitProtobufDefaults();
}

void protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl);
}
void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl() {
  protobuf_InitDefaults_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  static const char descriptor[] = {
      "\n-tensorflow/core/protobuf/worker_servic"
      "e.proto\022\017tensorflow.grpc\032%tensorflow/cor"
      "e/protobuf/worker.proto2\311\005\n\rWorkerServic"
      "e\022H\n\tGetStatus\022\034.tensorflow.GetStatusReq"
      "uest\032\035.tensorflow.GetStatusResponse\022T\n\rR"
      "egisterGraph\022 .tensorflow.RegisterGraphR"
      "equest\032!.tensorflow.RegisterGraphRespons"
      "e\022Z\n\017DeregisterGraph\022\".tensorflow.Deregi"
      "sterGraphRequest\032#.tensorflow.Deregister"
      "GraphResponse\022E\n\010RunGraph\022\033.tensorflow.R"
      "unGraphRequest\032\034.tensorflow.RunGraphResp"
      "onse\022Q\n\014CleanupGraph\022\037.tensorflow.Cleanu"
      "pGraphRequest\032 .tensorflow.CleanupGraphR"
      "esponse\022K\n\nCleanupAll\022\035.tensorflow.Clean"
      "upAllRequest\032\036.tensorflow.CleanupAllResp"
      "onse\022M\n\nRecvTensor\022\035.tensorflow.RecvTens"
      "orRequest\032\036.tensorflow.RecvTensorRespons"
      "e\"\000\022B\n\007Logging\022\032.tensorflow.LoggingReque"
      "st\032\033.tensorflow.LoggingResponse\022B\n\007Traci"
      "ng\022\032.tensorflow.TracingRequest\032\033.tensorf"
      "low.TracingResponseB3\n\032org.tensorflow.di"
      "struntimeB\023WorkerServiceProtosP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 880);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/worker_service.proto", &protobuf_RegisterTypes);
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_);
void protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_once_,
                 &protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
