// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/examples/android/proto/box_coder.proto

#ifndef PROTOBUF_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto__INCLUDED
#define PROTOBUF_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace org_tensorflow_demo {
class BoxCoderOptions;
class BoxCoderOptionsDefaultTypeInternal;
extern BoxCoderOptionsDefaultTypeInternal _BoxCoderOptions_default_instance_;
class BoxCoderPrior;
class BoxCoderPriorDefaultTypeInternal;
extern BoxCoderPriorDefaultTypeInternal _BoxCoderPrior_default_instance_;
class MultiBoxCoderOptions;
class MultiBoxCoderOptionsDefaultTypeInternal;
extern MultiBoxCoderOptionsDefaultTypeInternal _MultiBoxCoderOptions_default_instance_;
}  // namespace org_tensorflow_demo

namespace org_tensorflow_demo {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();
void protobuf_InitDefaults_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();

// ===================================================================

class BoxCoderPrior : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:org_tensorflow_demo.BoxCoderPrior) */ {
 public:
  BoxCoderPrior();
  virtual ~BoxCoderPrior();

  BoxCoderPrior(const BoxCoderPrior& from);

  inline BoxCoderPrior& operator=(const BoxCoderPrior& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoxCoderPrior& default_instance();

  static inline const BoxCoderPrior* internal_default_instance() {
    return reinterpret_cast<const BoxCoderPrior*>(
               &_BoxCoderPrior_default_instance_);
  }

  void Swap(BoxCoderPrior* other);

  // implements Message ----------------------------------------------

  inline BoxCoderPrior* New() const PROTOBUF_FINAL { return New(NULL); }

  BoxCoderPrior* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BoxCoderPrior& from);
  void MergeFrom(const BoxCoderPrior& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BoxCoderPrior* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float mean = 1 [default = 0];
  bool has_mean() const;
  void clear_mean();
  static const int kMeanFieldNumber = 1;
  float mean() const;
  void set_mean(float value);

  // optional float stddev = 2 [default = 1];
  bool has_stddev() const;
  void clear_stddev();
  static const int kStddevFieldNumber = 2;
  float stddev() const;
  void set_stddev(float value);

  // @@protoc_insertion_point(class_scope:org_tensorflow_demo.BoxCoderPrior)
 private:
  void set_has_mean();
  void clear_has_mean();
  void set_has_stddev();
  void clear_has_stddev();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float mean_;
  float stddev_;
  friend void  protobuf_InitDefaults_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();

};
// -------------------------------------------------------------------

class BoxCoderOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:org_tensorflow_demo.BoxCoderOptions) */ {
 public:
  BoxCoderOptions();
  virtual ~BoxCoderOptions();

  BoxCoderOptions(const BoxCoderOptions& from);

  inline BoxCoderOptions& operator=(const BoxCoderOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoxCoderOptions& default_instance();

  static inline const BoxCoderOptions* internal_default_instance() {
    return reinterpret_cast<const BoxCoderOptions*>(
               &_BoxCoderOptions_default_instance_);
  }

  void Swap(BoxCoderOptions* other);

  // implements Message ----------------------------------------------

  inline BoxCoderOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  BoxCoderOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BoxCoderOptions& from);
  void MergeFrom(const BoxCoderOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BoxCoderOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .org_tensorflow_demo.BoxCoderPrior priors = 1;
  int priors_size() const;
  void clear_priors();
  static const int kPriorsFieldNumber = 1;
  const ::org_tensorflow_demo::BoxCoderPrior& priors(int index) const;
  ::org_tensorflow_demo::BoxCoderPrior* mutable_priors(int index);
  ::org_tensorflow_demo::BoxCoderPrior* add_priors();
  ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderPrior >*
      mutable_priors();
  const ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderPrior >&
      priors() const;

  // optional bool use_corners = 2 [default = true];
  bool has_use_corners() const;
  void clear_use_corners();
  static const int kUseCornersFieldNumber = 2;
  bool use_corners() const;
  void set_use_corners(bool value);

  // optional bool use_width_height = 3 [default = false];
  bool has_use_width_height() const;
  void clear_use_width_height();
  static const int kUseWidthHeightFieldNumber = 3;
  bool use_width_height() const;
  void set_use_width_height(bool value);

  // optional bool use_center = 4 [default = false];
  bool has_use_center() const;
  void clear_use_center();
  static const int kUseCenterFieldNumber = 4;
  bool use_center() const;
  void set_use_center(bool value);

  // optional bool use_area = 5 [default = false];
  bool has_use_area() const;
  void clear_use_area();
  static const int kUseAreaFieldNumber = 5;
  bool use_area() const;
  void set_use_area(bool value);

  // @@protoc_insertion_point(class_scope:org_tensorflow_demo.BoxCoderOptions)
 private:
  void set_has_use_corners();
  void clear_has_use_corners();
  void set_has_use_width_height();
  void clear_has_use_width_height();
  void set_has_use_center();
  void clear_has_use_center();
  void set_has_use_area();
  void clear_has_use_area();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderPrior > priors_;
  bool use_width_height_;
  bool use_center_;
  bool use_area_;
  bool use_corners_;
  friend void  protobuf_InitDefaults_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();

};
// -------------------------------------------------------------------

class MultiBoxCoderOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:org_tensorflow_demo.MultiBoxCoderOptions) */ {
 public:
  MultiBoxCoderOptions();
  virtual ~MultiBoxCoderOptions();

  MultiBoxCoderOptions(const MultiBoxCoderOptions& from);

  inline MultiBoxCoderOptions& operator=(const MultiBoxCoderOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MultiBoxCoderOptions& default_instance();

  static inline const MultiBoxCoderOptions* internal_default_instance() {
    return reinterpret_cast<const MultiBoxCoderOptions*>(
               &_MultiBoxCoderOptions_default_instance_);
  }

  void Swap(MultiBoxCoderOptions* other);

  // implements Message ----------------------------------------------

  inline MultiBoxCoderOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  MultiBoxCoderOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MultiBoxCoderOptions& from);
  void MergeFrom(const MultiBoxCoderOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MultiBoxCoderOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .org_tensorflow_demo.BoxCoderOptions box_coder = 1;
  int box_coder_size() const;
  void clear_box_coder();
  static const int kBoxCoderFieldNumber = 1;
  const ::org_tensorflow_demo::BoxCoderOptions& box_coder(int index) const;
  ::org_tensorflow_demo::BoxCoderOptions* mutable_box_coder(int index);
  ::org_tensorflow_demo::BoxCoderOptions* add_box_coder();
  ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderOptions >*
      mutable_box_coder();
  const ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderOptions >&
      box_coder() const;

  // @@protoc_insertion_point(class_scope:org_tensorflow_demo.MultiBoxCoderOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderOptions > box_coder_;
  friend void  protobuf_InitDefaults_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BoxCoderPrior

// optional float mean = 1 [default = 0];
inline bool BoxCoderPrior::has_mean() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BoxCoderPrior::set_has_mean() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BoxCoderPrior::clear_has_mean() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BoxCoderPrior::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float BoxCoderPrior::mean() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderPrior.mean)
  return mean_;
}
inline void BoxCoderPrior::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderPrior.mean)
}

// optional float stddev = 2 [default = 1];
inline bool BoxCoderPrior::has_stddev() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BoxCoderPrior::set_has_stddev() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BoxCoderPrior::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BoxCoderPrior::clear_stddev() {
  stddev_ = 1;
  clear_has_stddev();
}
inline float BoxCoderPrior::stddev() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderPrior.stddev)
  return stddev_;
}
inline void BoxCoderPrior::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderPrior.stddev)
}

// -------------------------------------------------------------------

// BoxCoderOptions

// repeated .org_tensorflow_demo.BoxCoderPrior priors = 1;
inline int BoxCoderOptions::priors_size() const {
  return priors_.size();
}
inline void BoxCoderOptions::clear_priors() {
  priors_.Clear();
}
inline const ::org_tensorflow_demo::BoxCoderPrior& BoxCoderOptions::priors(int index) const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderOptions.priors)
  return priors_.Get(index);
}
inline ::org_tensorflow_demo::BoxCoderPrior* BoxCoderOptions::mutable_priors(int index) {
  // @@protoc_insertion_point(field_mutable:org_tensorflow_demo.BoxCoderOptions.priors)
  return priors_.Mutable(index);
}
inline ::org_tensorflow_demo::BoxCoderPrior* BoxCoderOptions::add_priors() {
  // @@protoc_insertion_point(field_add:org_tensorflow_demo.BoxCoderOptions.priors)
  return priors_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderPrior >*
BoxCoderOptions::mutable_priors() {
  // @@protoc_insertion_point(field_mutable_list:org_tensorflow_demo.BoxCoderOptions.priors)
  return &priors_;
}
inline const ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderPrior >&
BoxCoderOptions::priors() const {
  // @@protoc_insertion_point(field_list:org_tensorflow_demo.BoxCoderOptions.priors)
  return priors_;
}

// optional bool use_corners = 2 [default = true];
inline bool BoxCoderOptions::has_use_corners() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BoxCoderOptions::set_has_use_corners() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BoxCoderOptions::clear_has_use_corners() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BoxCoderOptions::clear_use_corners() {
  use_corners_ = true;
  clear_has_use_corners();
}
inline bool BoxCoderOptions::use_corners() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderOptions.use_corners)
  return use_corners_;
}
inline void BoxCoderOptions::set_use_corners(bool value) {
  set_has_use_corners();
  use_corners_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderOptions.use_corners)
}

// optional bool use_width_height = 3 [default = false];
inline bool BoxCoderOptions::has_use_width_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BoxCoderOptions::set_has_use_width_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BoxCoderOptions::clear_has_use_width_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BoxCoderOptions::clear_use_width_height() {
  use_width_height_ = false;
  clear_has_use_width_height();
}
inline bool BoxCoderOptions::use_width_height() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderOptions.use_width_height)
  return use_width_height_;
}
inline void BoxCoderOptions::set_use_width_height(bool value) {
  set_has_use_width_height();
  use_width_height_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderOptions.use_width_height)
}

// optional bool use_center = 4 [default = false];
inline bool BoxCoderOptions::has_use_center() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BoxCoderOptions::set_has_use_center() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BoxCoderOptions::clear_has_use_center() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BoxCoderOptions::clear_use_center() {
  use_center_ = false;
  clear_has_use_center();
}
inline bool BoxCoderOptions::use_center() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderOptions.use_center)
  return use_center_;
}
inline void BoxCoderOptions::set_use_center(bool value) {
  set_has_use_center();
  use_center_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderOptions.use_center)
}

// optional bool use_area = 5 [default = false];
inline bool BoxCoderOptions::has_use_area() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BoxCoderOptions::set_has_use_area() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BoxCoderOptions::clear_has_use_area() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BoxCoderOptions::clear_use_area() {
  use_area_ = false;
  clear_has_use_area();
}
inline bool BoxCoderOptions::use_area() const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.BoxCoderOptions.use_area)
  return use_area_;
}
inline void BoxCoderOptions::set_use_area(bool value) {
  set_has_use_area();
  use_area_ = value;
  // @@protoc_insertion_point(field_set:org_tensorflow_demo.BoxCoderOptions.use_area)
}

// -------------------------------------------------------------------

// MultiBoxCoderOptions

// repeated .org_tensorflow_demo.BoxCoderOptions box_coder = 1;
inline int MultiBoxCoderOptions::box_coder_size() const {
  return box_coder_.size();
}
inline void MultiBoxCoderOptions::clear_box_coder() {
  box_coder_.Clear();
}
inline const ::org_tensorflow_demo::BoxCoderOptions& MultiBoxCoderOptions::box_coder(int index) const {
  // @@protoc_insertion_point(field_get:org_tensorflow_demo.MultiBoxCoderOptions.box_coder)
  return box_coder_.Get(index);
}
inline ::org_tensorflow_demo::BoxCoderOptions* MultiBoxCoderOptions::mutable_box_coder(int index) {
  // @@protoc_insertion_point(field_mutable:org_tensorflow_demo.MultiBoxCoderOptions.box_coder)
  return box_coder_.Mutable(index);
}
inline ::org_tensorflow_demo::BoxCoderOptions* MultiBoxCoderOptions::add_box_coder() {
  // @@protoc_insertion_point(field_add:org_tensorflow_demo.MultiBoxCoderOptions.box_coder)
  return box_coder_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderOptions >*
MultiBoxCoderOptions::mutable_box_coder() {
  // @@protoc_insertion_point(field_mutable_list:org_tensorflow_demo.MultiBoxCoderOptions.box_coder)
  return &box_coder_;
}
inline const ::google::protobuf::RepeatedPtrField< ::org_tensorflow_demo::BoxCoderOptions >&
MultiBoxCoderOptions::box_coder() const {
  // @@protoc_insertion_point(field_list:org_tensorflow_demo.MultiBoxCoderOptions.box_coder)
  return box_coder_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace org_tensorflow_demo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fexamples_2fandroid_2fproto_2fbox_5fcoder_2eproto__INCLUDED
